---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: konnectivity-agent-client
  annotations:
    gotemplating.fn.crossplane.io/composition-resource-name: addonValueKonnectivityAgentClient
    gotemplating.fn.crossplane.io/ready: "True"
  labels:
    addons.in-cloud.io/values: client
    addons.in-cloud.io/addon: konnectivity-agent
spec:
  values: |
    hostNetwork: true
    agent:
      extraArgs:
        proxy-server-host: {{ .Values.cluster.host }}
        proxy-server-port: 8132
