---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "capi.fullname" . }}-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "capi.fullname" . }}-serving-cert
  labels:
    {{- include "capi.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "capi.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-cluster-x-k8s-io-v1beta2-cluster
      port: {{ .Values.webhookService.port }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.cluster.cluster.x-k8s.io
  rules:
  - apiGroups:
    - cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "capi.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-addons-cluster-x-k8s-io-v1beta2-clusterresourceset
      port: {{ .Values.webhookService.port }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.clusterresourceset.addons.cluster.x-k8s.io
  rules:
  - apiGroups:
    - addons.cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterresourcesets
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "capi.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-runtime-cluster-x-k8s-io-v1beta2-extensionconfig
      port: {{ .Values.webhookService.port }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.extensionconfig.runtime.addons.cluster.x-k8s.io
  rules:
  - apiGroups:
    - runtime.cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - extensionconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "capi.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-cluster-x-k8s-io-v1beta2-machine
      port: {{ .Values.webhookService.port }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.machine.cluster.x-k8s.io
  rules:
  - apiGroups:
    - cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - machines
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "capi.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-cluster-x-k8s-io-v1beta2-machinedeployment
      port: {{ .Values.webhookService.port }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.machinedeployment.cluster.x-k8s.io
  rules:
  - apiGroups:
    - cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - machinedeployments
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "capi.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-cluster-x-k8s-io-v1beta2-machinehealthcheck
      port: {{ .Values.webhookService.port }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.machinehealthcheck.cluster.x-k8s.io
  rules:
  - apiGroups:
    - cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - machinehealthchecks
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "capi.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-cluster-x-k8s-io-v1beta2-machinepool
      port: {{ .Values.webhookService.port }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.machinepool.cluster.x-k8s.io
  rules:
  - apiGroups:
    - cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - machinepools
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "capi.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-cluster-x-k8s-io-v1beta2-machineset
      port: {{ .Values.webhookService.port }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.machineset.cluster.x-k8s.io
  rules:
  - apiGroups:
    - cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - machinesets
  sideEffects: None