{{- if .Values.secrets -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: signalilo-secrets
  labels:
    {{- include "signalilo.labels" . | nindent 4 }}
spec:
  data:
    {{- range $key, $value := .Values.secrets -}}
    {{ $key }}: {{ $value | b64enc | quote }}
    {{- end -}}
{{- end -}}
