apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./base.yaml

patches: []
  # - path: ./deployment.incloud-ui-oauth2-proxy.yaml
  #   target:
  #     kind: Deployment
  #     name: incloud-ui-oauth2-proxy

  # - path: ./service.incloud-ui-oauth2-proxy.yaml
  #   target:
  #     kind: Service
  #     name: incloud-ui-oauth2-proxy
