---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: addons-operator-default
  labels:
    addons.in-cloud.io/values: default
    addons.in-cloud.io/addon: addons-operator
spec:
  values: |
    certManager:
      enable: false
    manager:
      env:
      - name: ENABLE_WEBHOOKS
        value: false
      image:
        repository: prorobotech/addons-operator
        tag: feature-CLOUD-434-4a2d9e71
        pullPolicy: IfNotPresent
      tolerations:
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
    metrics:
      enable: false
      port: 8443

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: addons-operator-immutable
  labels:
    addons.in-cloud.io/values: immutable
    addons.in-cloud.io/addon: addons-operator
spec:
  values: ""

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: addons-operator-cert-manager
  labels:
    addons.in-cloud.io/values: cert-manager
    addons.in-cloud.io/addon: addons-operator
spec:
  values: |
    certManager:
      enable: true
    manager:
      env:
      - name: ENABLE_WEBHOOKS
        value: true
    metrics:
      enable: true
      port: 8443
