argocd:
  enabled: true
xK8s:
  enabled: true
certManager:
  enabled: true
crossplane:
  enabled: true
github:
  enabled: true
cilium:
  enabled: true
coreos:
  enabled: true
istio:
  enabled: true
inCloud:
  enabled: true
integreatly:
  enabled: true
victoriametrics:
  enabled: true
