---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: certificate-set-default
  labels:
    addons.in-cloud.io/values: default
    addons.in-cloud.io/addon: certificate-set
spec:
  values: |
    manager:
      args:
      - --cluster-wide
      image:
        repository: prorobotech/certificate-set
        tag: main-6b6710b3
        pullPolicy: IfNotPresent
      tolerations:
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
    metrics:
      enable: true
      port: 8443

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: certificate-set-immutable
  labels:
    addons.in-cloud.io/values: immutable
    addons.in-cloud.io/addon: certificate-set
spec:
  values: ""
