{{- range $componentName, $componentValue := .Values.components }}
{{- if $componentValue.enabled }}
{{- $monitoringValues := $componentValue.monitoring       | default dict }}
{{- $serviceValues    := $monitoringValues.secureService  | default dict }}
{{- $runtimeConfig    := $componentValue.runtimeConfig    | default dict }}
{{- $mathLabels       := include "crossplane-functions.match-labels" (dict 
  "kind" $componentValue.kind
  "name" $componentValue.name
) | fromYaml}}
{{- $runtimeConfig    = include "crossplane-functions.deep-merge" (list $runtimeConfig ($mathLabels)) | fromYaml }}

{{- $monitoringRaw    := dict }}
{{- if and $componentValue.enabled $monitoringValues.enabled }}
{{- $secretName       := printf "%s-%s-svc-tls" $.Release.Name $componentValue.name }}
{{- $monitoringRaw    = include "crossplane-functions.monitoring" (dict
  "securePort"    $serviceValues.port
  "upstreamPort"  $monitoringValues.internalMetricPort
  "secretName"    $secretName
) | toString | fromYaml}}

{{- end }}

---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: {{ $.Release.Name }}-{{ $componentValue.name }}
spec:
{{ include "crossplane-functions.deep-merge" (list $runtimeConfig $monitoringRaw) | nindent 2 }}
{{- end }}
{{- end }}
