composition:
  developmentMode: false
  compositionRevisionNumber: 0
  xaddonset:
    debug: false
  xcertificate:
    debug: false
  xcertificateset:
    debug: false

composite:
  addons:
    istiobase:
      targetRevision: 1.26.0

    grafana:
      targetRevision: vmcluster-tls
    victoriametricscluster:
      targetRevision: vmcluster-tls

xclusterComponents:
  client:
    enabled: false
