composition:
  developmentMode: false
  compositionRevisionNumber: 0
  xaddonset:
    debug: false
  xcertificate:
    debug: false
  xcertificateset:
    debug: false

composite:
  addons:
    common:
      targetRevision: feat/certset
    istiobase:
      targetRevision: 1.26.0

xclusterComponents:
  client:
    enabled: false
