composition:
  developmentMode: false
  compositionRevisionNumber: 0
  xaddonset:
    debug: false
  xcertificate:
    debug: false
  xcertificateset:
    debug: false

composite:
  addons:
    istiobase:
      targetRevision: 1.26.0
    common:
      targetRevision: feature/monitoring # TODO: merge to HEAD
    # gitlabRefs
    begetcmprovider:
      targetRevision: monitoring # TODO: merge to HEAD
    ccm:
      targetRevision: HEAD
    crossplanexcluster:
      targetRevision: HEAD
    csrc:
      targetRevision: HEAD
    capiclusterclass:
      targetRevision: HEAD

xclusterComponents:
  client:
    enabled: false
