composition:
  developmentMode: false
  compositionRevisionNumber: 0
  xaddonset:
    debug: false
  xcertificate:
    debug: false
  xcertificateset:
    debug: false

composite:
  addons:
    common:
      targetRevision: HEAD
    crossplane:
      targetRevision: feature/monitoring # TODO: merge to HEAD
    istiobase:
      targetRevision: 1.26.0
    prometheusadapter:
      targetRevision: 4.14.1
    begetCmProvider:
      targetRevision: monitoring # TODO: merge to HEAD

xclusterComponents:
  client:
    enabled: false
