composition:
  developmentMode: false
  compositionRevisionNumber: 0
  xaddonset:
    debug: false
  xcertificate:
    debug: false
  xcertificateset:
    debug: false

composite:
  addons:
    common:
      targetRevision: feature/monitoring
    begetcmprovider:
      targetRevision: monitoring # TODO: merge to HEAD
    ccm:
      targetRevision: HEAD # TODO: delete
    crossplanexcluster:
      targetRevision: HEAD # TODO: delete
    csrc:
      targetRevision: HEAD # TODO: delete
    capiclusterclass:
      targetRevision: HEAD # TODO: delete
    istiobase:
      targetRevision: 1.26.0
    prometheusadapter:
      targetRevision: 4.14.1

xclusterComponents:
  client:
    enabled: false
