composition:
  developmentMode: false
  compositionRevisionNumber: 0
  xaddonset:
    debug: false
  xcertificate:
    debug: false
  xcertificateset:
    debug: false

composite:
  addons:
    istiobase:
      targetRevision: 1.26.0
    begetcmprovider:
      targetRevision: monitoring # TODO: merge to HEAD

xclusterComponents:
  client:
    enabled: false
