composition:
  developmentMode: false
  compositionRevisionNumber: 0
  xaddonset:
    debug: false
  xcertificate:
    debug: false
  xcertificateset:
    debug: false

composite:
  addons:
    ccm: HEAD
    csrc: HEAD
    common:
      targetRevision: feat/certset
    istiobase:
      targetRevision: 1.26.0
    begetcmprovider: HEAD
    crossplanexcluster: HEAD
    certcontrollermanager: HEAD

xclusterComponents:
  client:
    enabled: false
