composition:
  developmentMode: false
  compositionRevisionNumber: 0
  xaddonset:
    debug: false
  xcertificate:
    debug: false
  xcertificateset:
    debug: false

composite:
  addons:
    common:
      targetRevision: v0.0.4

    # feature/alerting
    clickhouseinserter:
      targetRevision: feature/alerting
    crossplanecompositions:
      targetRevision: feature/alerting
    victoriametricsagent:
      targetRevision: feature/alerting
    victoriametricsalert:
      targetRevision: feature/alerting
    victoriametricsalertrules:
      targetRevision: feature/alerting
    victoriametricscluster:
      targetRevision: feature/alerting

    # external repos
    ccm:
      targetRevision: HEAD
    certcontrollermanager:
      targetRevision: HEAD
    csrc:
      targetRevision: HEAD
    istiobase:
      targetRevision: 1.26.0
    secretcopyoperator:
      targetRevision: HEAD

xclusterComponents:
  client:
    enabled: false
