composition:
  developmentMode: false
  compositionRevisionNumber: 0
  xaddonset:
    debug: false
  xcertificate:
    debug: false
  xcertificateset:
    debug: false

composite:
  addons:
    common:
      targetRevision: v0.0.4

    # feature/alerting
    crossplanecompositions:
      targetRevision: feature/alerting
    signalilo:
      targetRevision: feature/alerting
    victoriametricsalertmanager:
      targetRevision: feature/alerting

    # external repos
    addonsoperator:
      targetRevision: HEAD
    begetcmprovider: 
      targetRevision: feat/new-api-version
    capiclusterclass:
      targetRevision: HEAD
    ccm:
      targetRevision: HEAD
    certcontrollermanager:
      targetRevision: HEAD
    csrc:
      targetRevision: HEAD
    istiobase:
      targetRevision: 1.26.0
    secretcopyoperator:
      targetRevision: HEAD

xclusterComponents:
  client:
    enabled: false
