composition:
  developmentMode: false
  compositionRevisionNumber: 0
  xaddonset:
    debug: false
  xcertificate:
    debug: false
  xcertificateset:
    debug: false

composite:
  addons:
    ccm:
      targetRevision: HEAD
    csrc:
      targetRevision: HEAD
    common:
      targetRevision: HEAD
    istiobase:
      targetRevision: 1.26.0
    begetcmprovider:
      targetRevision: HEAD
    crossplanexcluster:
      targetRevision: HEAD
    certcontrollermanager:
      targetRevision: HEAD
    capiclusterclass:
      targetRevision: HEAD

xclusterComponents:
  client:
    enabled: false
