composition:
  developmentMode: false
  compositionRevisionNumber: 0
  xaddonset:
    debug: false
  xcertificate:
    debug: false
  xcertificateset:
    debug: false

composite:
  addons:
    common:
      targetRevision: feature/plugin-enabled-over-values

    # external repos
    begetcmprovider: 
      targetRevision: HEAD
    capiclusterclass:
      targetRevision: HEAD
    ccm:
      targetRevision: HEAD
    certcontrollermanager:
      targetRevision: HEAD
    crossplanexcluster:
      targetRevision: HEAD
    csrc:
      targetRevision: HEAD
    istiobase:
      targetRevision: 1.26.0
    secretcopyoperator:
      targetRevision: feature/CLOUD-409

xclusterComponents:
  client:
    enabled: false
