composition:
  developmentMode: false
  compositionRevisionNumber: 0
  xaddonset:
    debug: false
  xcertificate:
    debug: false
  xcertificateset:
    debug: false

composite:
  addons:
    common:
      targetRevision: v0.0.3

    # external repos
    begetcmprovider: 
      targetRevision: HEAD
    capiclusterclass:
      targetRevision: HEAD
    ccm:
      targetRevision: HEAD
    certcontrollermanager:
      targetRevision: HEAD
    crossplanexcluster:
      targetRevision: v0.0.3
    crossplanecompositions:
      targetRevision: feat/copy-operator
    csrc:
      targetRevision: HEAD
    istiobase:
      targetRevision: 1.26.0
    secretcopyoperator:
      targetRevision: v0.0.3
    capi:
      targetRevision: feat/copy-operator
    capikubeadmbootstrap:
      targetRevision: feat/copy-operator
    capikubeadmcontrolplane:
      targetRevision: feat/copy-operator

xclusterComponents:
  client:
    enabled: false
