apiVersion: addons.in-cloud.io/v1alpha1
kind: Addon
metadata:
  name: prometheus-node-exporter
  annotations:
    gotemplating.fn.crossplane.io/composition-resource-name: addonPrometheusNodeExporter
    gotemplating.fn.crossplane.io/ready: "True"
spec:
  chart: ""
  path: "helm-chart-sources/prometheus-node-exporter"
  pluginName: helm-with-values
  repoURL: "https://github.com/LTD-Beget/kaas-helm-charts"
  version: "HEAD"
  targetCluster: in-cluster
  targetNamespace: "beget-prometheus-node-exporter"
  variables:
    cluster_name: in-cluster
  valuesSources: []
  initDependencies:
    - name: vm-operator
      criteria:
        - jsonPath: $.status.conditions[?(@.type=='Ready')].status
          operator: Equal
          value: "True"
  backend: 
    type: "argocd"
    namespace: "beget-argocd"
    project: "default"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      managedNamespaceMetadata:
        labels:
          in-cloud.io/caBundle: approved
          in-cloud.io/clusterName: infra
      syncOptions:
        - CreateNamespace=true
  valuesSelectors:
    - name: default
      priority: 0
      matchLabels:
        addons.in-cloud.io/values: default
        addons.in-cloud.io/addon: prometheus-node-exporter
    - name: infra
      priority: 10
      matchLabels:
        addons.in-cloud.io/values: infra
        addons.in-cloud.io/addon: prometheus-node-exporter

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: prometheus-node-exporter-default
  annotations:
    gotemplating.fn.crossplane.io/composition-resource-name: addonValuePrometheusNodeExporterDefault
    gotemplating.fn.crossplane.io/ready: "True"
  labels:
    addons.in-cloud.io/values: default
    addons.in-cloud.io/addon: prometheus-node-exporter
spec:
  values: |
    prometheus-node-exporter:
      service:
        enabled: true
        port: 9100
        labels:
          beget.com/prometheus-job: node-exporter
      containerSecurityContext:
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
      serviceAccount:
        automountServiceAccountToken: true
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 512m
          memory: 256Mi

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: prometheus-node-exporter-infra
  annotations:
    gotemplating.fn.crossplane.io/composition-resource-name: addonValuePrometheusNodeExporterInfra
    gotemplating.fn.crossplane.io/ready: "True"
  labels:
    addons.in-cloud.io/values: infra
    addons.in-cloud.io/addon: prometheus-node-exporter
spec:
  values: |
    prometheus-node-exporter:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: prometheus-node-exporter-cert-manager
  annotations:
    gotemplating.fn.crossplane.io/composition-resource-name: addonValuePrometheusNodeExporterCertManager
    gotemplating.fn.crossplane.io/ready: "True"
  labels:
    addons.in-cloud.io/values: cert-manager
    addons.in-cloud.io/addon: prometheus-node-exporter
spec:
  values: |
    argocdPlugins:
      kustomize: true
    monitoring:
      secureService:
        enabled: true
        issuer:
          name: selfsigned-cluster-issuer

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: prometheus-node-exporter-vm-operator
  annotations:
    gotemplating.fn.crossplane.io/composition-resource-name: addonValuePrometheusNodeExporterVmOperator
    gotemplating.fn.crossplane.io/ready: "True"
  labels:
    addons.in-cloud.io/values: vm-operator
    addons.in-cloud.io/addon: prometheus-node-exporter
spec:
  values: |
    monitoring:
      enabled: true

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: prometheus-node-exporter-system
  annotations:
    gotemplating.fn.crossplane.io/composition-resource-name: addonValuePrometheusNodeExporterSystem
    gotemplating.fn.crossplane.io/ready: "True"
  labels:
    addons.in-cloud.io/values: system
    addons.in-cloud.io/addon: prometheus-node-exporter
spec:
  values: |
    prometheus-prometheus-node-exporter:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/argocd"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/crossplane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/vm-stream"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/vm-data"
          operator: "Exists"
          effect: "NoSchedule"

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonPhase
metadata:
  annotations:
    gotemplating.fn.crossplane.io/composition-resource-name: addonPhasePrometheusNodeExporter
    gotemplating.fn.crossplane.io/ready: "True"
  name: prometheus-node-exporter
spec:
  rules:
    - name: cert-manager
      criteria:
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cert-manager
          jsonPath: $.status.conditions[?(@.type=='Ready')].status
          operator: Equal
          value: "True"
      selector:
        name: cert-manager
        priority: 20
        matchLabels:
          addons.in-cloud.io/values: cert-manager
          addons.in-cloud.io/addon: prometheus-node-exporter
    - name: vm-operator
      criteria:
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: vm-operator
          jsonPath: $.status.conditions[?(@.type=='Ready')].status
          operator: Equal
          value: "True"
      selector:
        name: vm-operator
        priority: 30
        matchLabels:
          addons.in-cloud.io/values: vm-operator
          addons.in-cloud.io/addon: prometheus-node-exporter
    - name: system
      criteria:
        - source:
            apiVersion: v1
            kind: ConfigMap
            name: parameters
            namespace: beget-system
          jsonPath: $.data.systemEnabled
          operator: Equal
          value: "True"
      selector:
        name: system
        priority: 50
        matchLabels:
          addons.in-cloud.io/values: system
          addons.in-cloud.io/addon: prometheus-node-exporter

