apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
    annotations:
        {{- if .Values.certManager.enable }}
        cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "addon-operator.resourceName" (dict "suffix" "serving-cert" "context" $) }}
        {{- end }}
    name: {{ include "addon-operator.resourceName" (dict "suffix" "validating-webhook-configuration" "context" $) }}
webhooks:
    - admissionReviewVersions:
        - v1
      clientConfig:
        service:
            name: {{ include "addon-operator.resourceName" (dict "suffix" "webhook-service" "context" $) }}
            namespace: {{ .Release.Namespace }}
            path: /validate-addons-in-cloud-io-v1alpha1-addon
      failurePolicy: Fail
      name: vaddon-v1alpha1.kb.io
      rules:
        - apiGroups:
            - addons.in-cloud.io
          apiVersions:
            - v1alpha1
          operations:
            - CREATE
            - UPDATE
          resources:
            - addons
      sideEffects: None
    - admissionReviewVersions:
        - v1
      clientConfig:
        service:
            name: {{ include "addon-operator.resourceName" (dict "suffix" "webhook-service" "context" $) }}
            namespace: {{ .Release.Namespace }}
            path: /validate-addons-in-cloud-io-v1alpha1-addonphase
      failurePolicy: Fail
      name: vaddonphase-v1alpha1.kb.io
      rules:
        - apiGroups:
            - addons.in-cloud.io
          apiVersions:
            - v1alpha1
          operations:
            - CREATE
            - UPDATE
          resources:
            - addonphases
      sideEffects: None
    - admissionReviewVersions:
        - v1
      clientConfig:
        service:
            name: {{ include "addon-operator.resourceName" (dict "suffix" "webhook-service" "context" $) }}
            namespace: {{ .Release.Namespace }}
            path: /validate-addons-in-cloud-io-v1alpha1-addonvalue
      failurePolicy: Fail
      name: vaddonvalue-v1alpha1.kb.io
      rules:
        - apiGroups:
            - addons.in-cloud.io
          apiVersions:
            - v1alpha1
          operations:
            - CREATE
            - UPDATE
          resources:
            - addonvalues
      sideEffects: None
