addons:
  addonOperator:
    enabled: true
  addons:
    enabled: true
  argocd:
    enabled: true
  certcontrollermanager:
    enabled: true
  certmanager:
    enabled: true
  certmanagercsidriver:
    enabled: true
  cilium:
    enabled: true
  coredns:
    enabled: true
  crossplane:
    enabled: false
  crossplanecompositions:
    enabled: false
  crossplanefunctions:
    enabled: false
  etcdbackup:
    enabled: true
  extraresources:
    enabled: true
  incloudui:
    enabled: true
  incloudwebresources:
    enabled: true
  istiobase:
    enabled: true
  istiod:
    enabled: true
  istiogw:
    enabled: true
  template:
    enabled: true
  test:
    enabled: true
  trustmanager:
    enabled: true
  vmoperator:
    enabled: true
  system:
    enabled: false
    clickhouseInserter: false
environment: infra
clientName: client-cluster
