{{ range $proxyName, $proxyValue := .Values.proxies }}
{{- if $proxyValue.enabled }}
{{- $proxyMergedValues  := ((deepCopy $.Values.default) | mergeOverwrite $proxyValue) -}}
{{- $proxyParsedName    := (include "docker-registry.registryname" $proxyName) -}}
{{- $config             := $proxyMergedValues.config | default dict -}}
{{- $storage            := $config.storage -}}
{{- $storageType        := (include "docker-registry.storage-type" $storage.type) -}}
{{- $storageValue       := (get ($storage | default dict) $storageType) -}}
{{- $log                := $config.log | default dict -}}
{{- $http               := $config.http | default dict -}}
{{- $tls                := $http.tls | default dict -}}
{{- $httpServiceName    := printf ":%v" $proxyMergedValues.service.port -}}
{{- $httpServicePrefix  := printf "%s%s/" $.Values.expose.repositoryPrefix $proxyParsedName -}}
{{- $intTls             := $.Values.internalTLS -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docker-registry.fullname" $ }}-{{ $proxyParsedName }}-config
  namespace: {{ $.Release.Namespace }}
  labels:
    registry: {{ include "docker-registry.fullname" $ }}-{{ $proxyParsedName }}
    {{- include "docker-registry.labels" $ | nindent 4 }}
stringData:
  config.yml: |-
    version: 0.1
    log:
      accesslog:
        disabled: {{ not $log.accesslog }}
      level: {{ $log.level }}
      formatter: {{ $log.formatter }}
      fields:
        service: registry-{{ $proxyParsedName }}
    storage:
      {{ $storageType }}:
        {{- with $storageValue }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
      tag:
        concurrencylimit: {{ $storage.tag.concurrencylimit | default 8 }}
      {{- with $storage.delete }}
      delete:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with $storage.redirect }}
      redirect:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with $storage.cache }}
      cache:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with $storage.maintenance }}
      maintenance:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
    {{- with $config.auth }}
    auth:
      {{- . | toYaml | nindent 6 }}
    {{- end }}
    {{- with $config.middleware }}
    middleware:
      {{- . | toYaml | nindent 6 }}
    {{- end }}
    http:
      addr: {{ $http.addr | default $httpServiceName }}
      prefix: {{ $http.prefix | default $httpServicePrefix }}
      {{- with $http.host }}
      host: {{ . }}
      {{- end }}
      {{- with $http.secret }}
      secret: {{ . }}
      {{- end }}
      {{- with $http.relativeurls }}
      relativeurls: {{ . }}
      {{- end }}
      {{- with $http.draintimeout }}
      draintimeout: {{ . }}
      {{- end }}
    {{- if or $tls (eq $intTls.certSource "certmanager") (eq $intTls.certSource "secret") }}
      tls:
        certificate: {{ $tls.certificate | default "/etc/distribution/tls/tls.crt" }}
        key: {{ $tls.key | default "/etc/distribution/tls/tls.key" }}
        {{- with $tls.clientcas }}
        clientcas:
          {{- . | toYaml | nindent 10 }}
        {{- end }}
        {{- with $tls.clientauth }}
        clientauth: {{ . }}
        {{- end }}
        {{- with $tls.letsencrypt }}
        letsencrypt:
          {{- . | toYaml | nindent 10 }}
        {{- end }}
    {{- end }}
    {{ if $proxyMergedValues.metrics.enabled }}
      debug:
        addr: :{{ $proxyMergedValues.metrics.port }}
        prometheus:
          enabled: true
          path: /metrics
    {{- end }}
      {{- with $http.headers }}
      headers:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with $http.h2c }}
      h2c:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with $http.prefix }}
      headers:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
    {{- with $config.redis }}
    redis:
      {{- . | toYaml | nindent 6 }}
    {{- end }}
    {{- with $config.health }}
    health:
      {{- . | toYaml | nindent 6 }}
    {{- end }}
    {{- with $config.proxy }}
    proxy:
      {{- . | toYaml | nindent 6 }}
    {{- end }}
    {{- with $config.validation }}
    validation:
      {{- . | toYaml | nindent 6 }}
    {{- end }}
{{- end }}
{{ end }}
