{{ $alertmanagerTLS := .Values.tls.alertmanager }}

{{- if $alertmanagerTLS.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ default "alertmanager-tls" $alertmanagerTLS.certificate.name }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ default "alertmanager-tls" $alertmanagerTLS.certificate.secretName }}
  duration: {{ default "8760h" $alertmanagerTLS.certificate.duration }}
  renewBefore: {{ default "720h" $alertmanagerTLS.certificate.renewBefore }}
  commonName: {{ default "alertmanager" $alertmanagerTLS.certificate.commonName }}
  {{- with $alertmanagerTLS.certificate.dnsNames }}
  dnsNames:
    {{- range $domain := . }}
    - {{ $domain | quote }}
    {{- end }}
  {{- end }}
  {{- with $alertmanagerTLS.certificate.ipAddresses }}
  ipAddresses:
    {{- range $ip := . }}
    - {{ $ip | quote }}
    {{- end }}
  {{- end }}
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    kind: {{ $alertmanagerTLS.issuer.kind }}
    name: {{ $alertmanagerTLS.issuer.name }}
{{- end }}
